### PR TITLE
Master 1.13.2

### PR DESCRIPTION
**Pull request by christilden**
Hi,

I have updated MoreOverlays so it compiles and runs on Minecraft 1.13.2, Forge 25, and ForgeGradle 3.  I am hopeful you will accept this pull request and also will publish the 1.13.2 version to Twitch.tv's Minecraft Mods repository.

Thanks,
Chris

### CODE REVIEW

**Comment by christilden** [comment]
Hi, I just wanted to follow-up on this. I am working on using this as a base to port to Minecraft 1.14.3 and I wanted to get your feedback to ensure this is on the right track.

**Comment by feldim2425** [comment]
Just wanted to know if there is any reason why the mod needs a boilerplate for configs? I didn't check on Forge 1.13 configs, did they remove them?

**Comment by christilden** [comment]
That’s a good question, upon code review (quickly on my phone), I am not 100% certain at the moment. There is for sure a change to event handling in Forge 25, which does require much of the refactoring. In order to get events working, I looked to the JEI mod as a template and all of the boilerplate is copied over from JEI mod.

That said, at the time I thought config needed refactoring as well, as all the startup was loading configs and it was failing with runtime errors. Now that I am reviewing it again; maybe not. I will review the config code again with this in mind and confirm.

**Comment by feldim2425** [comment]
Since 1.13.2 is already kind of outdated and the port for 1.14.4 is done, I don't think this is needed anymore.

**Pull request closed without merging**
